[package]
name = "online_chat"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.7.7"
serde = { version = "1.0.215", features = ["derive"] }
chrono = "0.4.38"
dashmap = "6.1.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"